const TRANSLATIONS = {
  en: {
    'nav.how': 'How It Works',
    'nav.tos': 'ToS',
    'nav.faq': 'FAQ',
    'nav.risk': 'Risks',
    'wallet.sub': '// choose your wallet //',
    'wallet.detecting': 'Detecting...',
    'wallet.detected': 'Detected ✔',
    'wallet.notFound': 'Not Detected',
    'hero.badge': '🔴 Live on Blockchain',
    'hero.sub': '// burn any erc20 token → claim 1 IB token instantly //',
    'stats.tokens': 'All Tokens Supported',
    'stats.ratio': 'Burn → IB Ratio',
    'stats.standard': 'Standard',
    'sidebar.guide': 'Quick Guide',
    'sidebar.step1': 'Connect your wallet to a supported network (auto-switch)',
    'sidebar.step2': 'Enter the ERC20 token address to burn',
    'sidebar.step3': 'Set the amount (min. 1 whole token)',
    'sidebar.step4': 'Approve & Burn — receive 1 IB token!',
    'sidebar.copy': 'Click to copy',
    'sidebar.explorer': 'View on Explorer ↗',
    'card.title': 'Burn & Claim',
    'card.tagline': '// approve → burn → receive 1 IB //',
    'card.connect': '⚡ Connect Wallet',
    'card.tokenLabel': 'Token Address to Burn',
    'card.pickerHint': '📂 SELECT FROM WALLET — or type manually below',
    'card.pickerLoading': '⏳ Loading tokens...',
    'card.tokenPlaceholder': '0x123... (or select from list above)',
    'card.amountLabel': 'Amount (Min 1 Token, Integer Only)',
    'card.tosAgree': 'I have read and agree to the',
    'card.tosTos': 'Terms of Service',
    'card.tosRisk': 'Risk Disclaimer',
    'card.burnBtn': '🔥 Approve & Burn',
    'card.statusWaiting': '[ Waiting for wallet connection... ]',
    'modal.how.title': 'How It Works',
    'modal.how.sub': '// burn & claim mechanism //',
    'modal.how.p1': 'Inpoburn Hub allows anyone to burn any ERC20 token on a supported blockchain network and receive 1 IB (Inpoburn) token in return.',
    'modal.how.steps': 'Steps',
    'modal.how.s1': '1. Connect your wallet to a supported network.',
    'modal.how.s2': '2. Enter the ERC20 token address you want to burn.',
    'modal.how.s3': '3. Set the amount (min. 1 whole token).',
    'modal.how.s4': '4. Click Approve & Burn — wallet will prompt two transactions: approve and burn.',
    'modal.how.s5': '5. After blockchain confirmation, 1 IB token is sent to your wallet automatically.',
    'modal.how.sc': 'Smart Contract',
    'modal.how.scp': 'The burn process is fully on-chain through the UniversalBurner contract. Burned tokens are sent to the dead address (0x000...dEaD) and cannot be recovered.',
    'modal.tos.title': 'Terms of Service',
    'modal.tos.sub': '// terms & conditions of use //',
    'modal.tos.h1': '1. Acceptance of Terms',
    'modal.tos.p1': 'By using Inpoburn Hub, you agree to all applicable terms and conditions. If you disagree, please stop using this service.',
    'modal.tos.h2': '2. Nature of Service',
    'modal.tos.p2': 'Inpoburn Hub is an experimental dApp running on supported blockchain networks. This service is provided "as is" without any warranty.',
    'modal.tos.h3': '3. User Risk',
    'modal.tos.p3': 'You are solely responsible for every transaction made. Burned tokens cannot be returned under any circumstance.',
    'modal.tos.h4': '4. Limitation of Liability',
    'modal.tos.p4': 'The Inpoburn team is not responsible for asset loss, transaction failure, or any damage arising from use of this platform.',
    'modal.tos.h5': '5. Prohibited Uses',
    'modal.tos.l1': 'Using the platform for illegal purposes',
    'modal.tos.l2': 'Attempting to exploit the smart contract',
    'modal.tos.l3': 'Spreading false information about the platform',
    'modal.tos.h6': '6. Service Changes',
    'modal.tos.p6': 'We reserve the right to modify, suspend, or terminate the service at any time without prior notice.',
    'modal.tos.h7': '7. Governing Law',
    'modal.tos.p7': 'These terms are governed by generally applicable international contract law principles.',
    'modal.faq.title': 'FAQ',
    'modal.faq.sub': '// frequently asked questions //',
    'modal.faq.q1': 'What tokens can be burned?',
    'modal.faq.a1': 'Any valid ERC20 token on the supported network. Make sure you have enough tokens and ETH for gas fees.',
    'modal.faq.q2': 'What is the minimum burn amount?',
    'modal.faq.a2': 'Minimum 1 whole token (integer). Decimal values like 0.5 or 0.9 are not accepted.',
    'modal.faq.q3': 'Can I receive more than 1 IB?',
    'modal.faq.a3': 'Each burn transaction yields exactly 1 IB token, regardless of how many tokens you burn.',
    'modal.faq.q4': 'Which networks are supported?',
    'modal.faq.a4': 'Inpoburn Hub supports major blockchain networks. The platform will show available network options when you connect your wallet.',
    'modal.faq.q5': 'Are there platform fees?',
    'modal.faq.a5': 'No platform fees. You only pay the gas fee of the blockchain network you are using.',
    'modal.faq.q6': 'What network does Inpoburn use?',
    'modal.faq.a6': 'Inpoburn Hub runs on Base Mainnet (Chain ID 8453). Make sure your wallet is connected to Base and you have ETH on Base for gas fees.',
    'modal.faq.q7': 'Why did my transaction fail?',
    'modal.faq.a7': 'Possible causes: invalid token, insufficient balance, or a congested network. Check your transaction on the block explorer.',
    'modal.risk.title': 'Risk Disclaimer',
    'modal.risk.sub': '// important risk information //',
    'modal.risk.h1': 'Irreversibility Risk',
    'modal.risk.p1': 'Blockchain transactions are permanent and cannot be reversed. Once tokens are burned, the process cannot be undone under any circumstance.',
    'modal.risk.h2': 'Smart Contract Risk',
    'modal.risk.p2': 'Although the contract has been tested, all smart contracts carry potential bugs. Use only amounts you are prepared to lose.',
    'modal.risk.h3': 'Network Risk',
    'modal.risk.p3': 'Network congestion can cause transactions to be delayed or fail. Gas fees can fluctuate significantly.',
    'modal.risk.h4': 'Token Risk',
    'modal.risk.p4': 'Always verify the token address before burning. Fake tokens or tokens with special mechanics (fee-on-transfer, rebase) may not work correctly.',
    'modal.risk.h5': 'Live Mainnet Platform',
    'modal.risk.p5': 'Inpoburn runs on Base Mainnet. IB tokens claimed are live on-chain and carry real network value. All transactions are final.',
    'modal.risk.h6': 'Important Advice',
    'modal.risk.l1': 'Always verify the contract address before transacting',
    'modal.risk.l2': 'Never burn tokens that have important value to you',
    'modal.risk.l3': 'Make sure you are connected to the correct network',
    'modal.risk.l4': 'Use the minimum amount for your first attempt',
    'footer.desc': 'Experimental burn-to-claim ERC20 token platform on blockchain. Not financial advice. Use wisely.',
    'footer.platform': 'Platform',
    'footer.legal': 'Legal',
    'footer.community': 'Community',
    'footer.faucet': 'Bridge to Base ↗',
    'footer.copy': '© 2025 Inpoburn Hub · All rights reserved · Base Mainnet',
    'lang.label': '🌐 Language',
    'status.waiting':     '[ Waiting for wallet connection... ]',
    'status.connecting':  '[ ⏳ Connecting wallet... ]',
    'status.checknet':    '[ 🔄 Checking network... ]',
    'status.addnet':      '[ ➕ Adding network to wallet... ]',
    'status.wrongnet':    '[ ⚠️ Wrong network, transactions may fail! ]',
    'status.connected':   '[ ✅ Connected to Base. Check ToS to start! ]',
    'status.wrongchain':  '[ ⚠️ Connected, but wrong network. Please switch manually. ]',
    'status.rejected':    '[ ❌ Connection rejected by user. ]',
    'status.failconn':    '[ ❌ Failed to connect wallet. ]',
    'status.notoken':     '[ ❌ Token address cannot be empty! ]',
    'status.badaddr':     '[ ❌ Invalid token address! ]',
    'status.badamount':   '[ ❌ Amount must be a whole number ≥ 1 (e.g. 1, 2, 10) ]',
    'status.notERC20':    '[ ❌ Not a valid ERC20 token on this network. ]',
    'status.txcancel':    '[ ❌ Transaction cancelled by user. ]',
    'status.notos':       '[ ❌ Please check ToS & Risk Disclaimer first! ]',
    'status.nosigner':    '[ ❌ Signer unavailable! ]',
    'status.checkdec':    '[ 🔍 Checking token decimals... ]',
    'status.checkallow':  '[ 🔓 Checking allowance... ]',
    'status.approving':   "[ ✍️ Click 'Approve' in your wallet... ]",
    'status.waitapprove': '[ ⏳ Waiting for approve confirmation... ]',
    'status.approved':    '[ ✅ Approval granted! ]',
    'status.burning':     '[ 🔥 Burning & Claiming... ]',
    'status.waitburn':    '[ ⏳ Waiting for blockchain confirmation... ]',
    'status.success':     '[ 🎉 Success! 1 IB has been sent to your wallet. ]',
    'status.selected':    (name, sym, bal) => `[ 🎯 Token selected: ${name} (${sym}) — balance: ${bal} ]`,
    'status.copied':      '✅ Copied!',
    'status.signinRequired': '[ 🔐 Sign the message in your wallet to unlock burn! ]',
    'status.signedIn':    '[ ✅ Verified! Wallet confirmed — ready to burn. ]',
    'status.signSkipped': '[ 🔒 Burn locked. Sign message to verify you\'re human. ]',
    'picker.detecting': '⏳ Detecting ERC20 tokens in wallet...',
    'picker.scanning':  (from, to, i, max) => `🔍 Scanning block ${from}–${to} (${i}/${max})...`,
    'picker.checking':  (n) => `🔎 Checking ${n} token contracts...`,
    'picker.none':      (n) => `⚠️ No ERC20 tokens detected in last ~${n} blocks.`,
    'picker.empty':     '⚠️ No ERC20 tokens with balance > 0 found.',
    'picker.error':     '❌ Failed to load tokens. Type address manually.',
    'wallet.install':   (key) => `${key} not detected.\nOpen installation page?`,
    'wallet.nowallet':  '[ ❌ No wallet detected. ]',
	'footer.community': 'Community',
    'footer.coffee': '☕ Buy Me a Coffee (Base/ETH)',
    'footer.copyMsg': 'Address Copied! Thanks for the coffee! ☕',
  },
  id: {
    'nav.how': 'Cara Kerja',
    'nav.tos': 'ToS',
    'nav.faq': 'FAQ',
    'nav.risk': 'Risiko',
    'wallet.sub': '// pilih dompet kamu //',
    'wallet.detecting': 'Mendeteksi...',
    'wallet.detected': 'Terdeteksi ✔',
    'wallet.notFound': 'Tidak Terdeteksi',
    'hero.sub': '// bakar token erc20 apapun → klaim 1 IB token seketika //',
    'stats.tokens': 'Token Didukung',
    'stats.ratio': 'Rasio Burn → IB',
    'stats.standard': 'Standar',
    'sidebar.guide': 'Panduan Cepat',
    'sidebar.step1': 'Hubungkan wallet ke jaringan yang didukung (auto-switch)',
    'sidebar.step2': 'Masukkan alamat token ERC20 yang ingin dibakar',
    'sidebar.step3': 'Tentukan jumlah (min. 1 token bulat)',
    'sidebar.step4': 'Approve & Burn — terima 1 IB token!',
    'sidebar.copy': 'Klik untuk copy',
    'sidebar.explorer': 'Lihat di Explorer ↗',
    'card.title': 'Burn & Klaim',
    'card.tagline': '// approve → bakar → terima 1 IB //',
    'card.connect': '⚡ Hubungkan Wallet',
    'card.tokenLabel': 'Alamat Token yang Akan Dibakar',
    'card.pickerHint': '📂 PILIH DARI WALLET — atau ketik manual di bawah',
    'card.pickerLoading': '⏳ Memuat token...',
    'card.tokenPlaceholder': '0x123... (atau pilih dari daftar atas)',
    'card.amountLabel': 'Jumlah (Min 1 Token, Bilangan Bulat)',
    'card.tosAgree': 'Saya telah membaca dan menyetujui',
    'card.tosTos': 'Syarat & Ketentuan',
    'card.tosRisk': 'Disclaimer Risiko',
    'card.burnBtn': '🔥 Setujui & Bakar',
    'card.statusWaiting': '[ Menunggu koneksi wallet... ]',
    'modal.how.title': 'Cara Kerja',
    'modal.how.sub': '// mekanisme burn & claim //',
    'modal.how.p1': 'Inpoburn Hub memungkinkan siapa saja untuk membakar token ERC20 apapun di jaringan blockchain yang didukung dan menerima 1 IB (Inpoburn) token sebagai gantinya.',
    'modal.how.steps': 'Langkah-langkah',
    'modal.how.s1': '1. Hubungkan wallet kamu ke jaringan yang didukung.',
    'modal.how.s2': '2. Masukkan alamat token ERC20 yang ingin dibakar.',
    'modal.how.s3': '3. Tentukan jumlah token (min. 1 token bulat).',
    'modal.how.s4': '4. Klik Approve & Burn — wallet akan meminta dua transaksi: approve dan burn.',
    'modal.how.s5': '5. Setelah konfirmasi blockchain, 1 IB token masuk ke wallet kamu secara otomatis.',
    'modal.how.sc': 'Smart Contract',
    'modal.how.scp': 'Proses burn dilakukan sepenuhnya on-chain melalui kontrak UniversalBurner. Token yang dibakar dikirim ke alamat dead (0x000...dEaD) dan tidak dapat dikembalikan.',
    'modal.tos.title': 'Syarat & Ketentuan',
    'modal.tos.sub': '// syarat & ketentuan penggunaan //',
    'modal.tos.h1': '1. Penerimaan Syarat',
    'modal.tos.p1': 'Dengan menggunakan Inpoburn Hub, kamu menyetujui seluruh syarat dan ketentuan yang berlaku. Jika tidak setuju, harap hentikan penggunaan layanan ini.',
    'modal.tos.h2': '2. Sifat Layanan',
    'modal.tos.p2': 'Inpoburn Hub adalah dApp eksperimental yang berjalan di jaringan blockchain yang didukung. Layanan ini disediakan "sebagaimana adanya" tanpa jaminan apapun.',
    'modal.tos.h3': '3. Risiko Pengguna',
    'modal.tos.p3': 'Kamu sepenuhnya bertanggung jawab atas setiap transaksi yang dilakukan. Token yang sudah dibakar tidak dapat dikembalikan dalam kondisi apapun.',
    'modal.tos.h4': '4. Batasan Tanggung Jawab',
    'modal.tos.p4': 'Tim Inpoburn tidak bertanggung jawab atas kehilangan aset, kegagalan transaksi, atau kerugian apapun yang timbul dari penggunaan platform ini.',
    'modal.tos.h5': '5. Penggunaan yang Dilarang',
    'modal.tos.l1': 'Menggunakan platform untuk tujuan ilegal',
    'modal.tos.l2': 'Mencoba mengeksploitasi smart contract',
    'modal.tos.l3': 'Menyebarkan informasi palsu tentang platform',
    'modal.tos.h6': '6. Perubahan Layanan',
    'modal.tos.p6': 'Kami berhak mengubah, menangguhkan, atau menghentikan layanan kapan saja tanpa pemberitahuan sebelumnya.',
    'modal.tos.h7': '7. Hukum yang Berlaku',
    'modal.tos.p7': 'Syarat ini diatur oleh prinsip-prinsip umum hukum kontrak yang berlaku secara internasional.',
    'modal.faq.title': 'FAQ',
    'modal.faq.sub': '// pertanyaan yang sering diajukan //',
    'modal.faq.q1': 'Token apa yang bisa dibakar?',
    'modal.faq.a1': 'Semua token ERC20 yang valid di jaringan yang didukung. Pastikan kamu memiliki cukup token dan ETH untuk gas fee.',
    'modal.faq.q2': 'Berapa minimal token yang bisa dibakar?',
    'modal.faq.a2': 'Minimal 1 token bulat (integer). Nilai desimal seperti 0.5 atau 0.9 tidak diterima.',
    'modal.faq.q3': 'Apakah saya bisa mendapat lebih dari 1 IB?',
    'modal.faq.a3': 'Setiap transaksi burn menghasilkan tepat 1 IB token, tidak peduli berapa banyak token yang kamu bakar.',
    'modal.faq.q4': 'Network apa yang didukung?',
    'modal.faq.a4': 'Inpoburn Hub mendukung jaringan blockchain utama. Platform akan menampilkan pilihan network yang tersedia saat kamu menghubungkan wallet.',
    'modal.faq.q5': 'Apakah ada biaya platform?',
    'modal.faq.a5': 'Tidak ada biaya platform. Kamu hanya membayar gas fee jaringan blockchain yang sedang kamu gunakan.',
    'modal.faq.q6': 'Network apa yang digunakan Inpoburn?',
    'modal.faq.a6': 'Inpoburn Hub berjalan di Base Mainnet (Chain ID 8453). Pastikan wallet kamu terhubung ke Base dan memiliki ETH di Base untuk membayar gas fee.',
    'modal.faq.q7': 'Transaksi saya gagal, kenapa?',
    'modal.faq.a7': 'Kemungkinan penyebab: token tidak valid, saldo tidak cukup, atau jaringan sedang sibuk. Cek status transaksi di block explorer.',
    'modal.risk.title': 'Disclaimer Risiko',
    'modal.risk.sub': '// informasi risiko penting //',
    'modal.risk.h1': 'Risiko Irreversibilitas',
    'modal.risk.p1': 'Transaksi blockchain bersifat permanen dan tidak dapat dibatalkan. Setelah token dibakar, proses tidak bisa diurungkan dalam kondisi apapun.',
    'modal.risk.h2': 'Risiko Smart Contract',
    'modal.risk.p2': 'Meskipun kontrak telah diuji, semua smart contract mengandung potensi bug. Gunakan dengan jumlah yang kamu siap kehilangan.',
    'modal.risk.h3': 'Risiko Jaringan',
    'modal.risk.p3': 'Kongestis jaringan dapat menyebabkan transaksi tertunda atau gagal. Gas fee dapat berfluktuasi secara signifikan.',
    'modal.risk.h4': 'Risiko Token',
    'modal.risk.p4': 'Pastikan kamu memverifikasi alamat token sebelum burn. Token palsu atau token dengan mekanisme khusus (fee-on-transfer, rebase) mungkin tidak bekerja dengan benar.',
    'modal.risk.h5': 'Platform Mainnet Live',
    'modal.risk.p5': 'Inpoburn berjalan di Base Mainnet. Token IB yang diklaim bersifat on-chain nyata. Seluruh transaksi bersifat final.',
    'modal.risk.h6': 'Saran Penting',
    'modal.risk.l1': 'Selalu verifikasi alamat kontrak sebelum bertransaksi',
    'modal.risk.l2': 'Jangan pernah burn token yang memiliki nilai penting bagimu',
    'modal.risk.l3': 'Pastikan kamu terhubung ke network yang benar',
    'modal.risk.l4': 'Gunakan jumlah minimal untuk percobaan pertama',
    'footer.desc': 'Platform burn-to-claim ERC20 token eksperimental di blockchain. Bukan financial advice. Gunakan dengan bijak.',
    'footer.platform': 'Platform',
    'footer.legal': 'Legal',
    'footer.community': 'Komunitas',
    'footer.faucet': 'Bridge to Base ↗',
    'footer.copy': '© 2025 Inpoburn Hub · Hak cipta dilindungi · Base Mainnet',
    'lang.label': '🌐 Bahasa',
    'status.waiting':     '[ Menunggu koneksi wallet... ]',
    'status.connecting':  '[ ⏳ Menghubungkan wallet... ]',
    'status.checknet':    '[ 🔄 Mengecek network... ]',
    'status.addnet':      '[ ➕ Menambahkan network ke wallet... ]',
    'status.wrongnet':    '[ ⚠️ Network tidak sesuai, transaksi mungkin gagal! ]',
    'status.connected':   '[ ✅ Terhubung ke Base. Centang ToS untuk mulai! ]',
    'status.wrongchain':  '[ ⚠️ Terhubung, tapi network tidak sesuai. Harap ganti manual. ]',
    'status.rejected':    '[ ❌ Koneksi ditolak oleh pengguna. ]',
    'status.failconn':    '[ ❌ Gagal menghubungkan wallet. ]',
    'status.notoken':     '[ ❌ Token address tidak boleh kosong! ]',
    'status.badaddr':     '[ ❌ Alamat Token tidak valid! ]',
    'status.badamount':   '[ ❌ Jumlah harus bilangan bulat minimal 1 (contoh: 1, 2, 10) ]',
    'status.notERC20':    '[ ❌ Bukan token ERC20 valid di network ini. ]',
    'status.txcancel':    '[ ❌ Transaksi dibatalkan oleh pengguna. ]',
    'status.notos':       '[ ❌ Harap centang ToS & Risk Disclaimer terlebih dahulu! ]',
    'status.nosigner':    '[ ❌ Signer tidak tersedia! ]',
    'status.checkdec':    '[ 🔍 Mengecek desimal token... ]',
    'status.checkallow':  '[ 🔓 Mengecek izin (allowance)... ]',
    'status.approving':   "[ ✍️ Klik 'Approve' di wallet kamu... ]",
    'status.waitapprove': '[ ⏳ Menunggu konfirmasi approve... ]',
    'status.approved':    '[ ✅ Izin diberikan! ]',
    'status.burning':     '[ 🔥 Proses Burn & Claim... ]',
    'status.waitburn':    '[ ⏳ Menunggu konfirmasi blockchain... ]',
    'status.success':     '[ 🎉 Berhasil! 1 IB telah masuk ke dompet Anda. ]',
    'status.selected':    (name, sym, bal) => `[ 🎯 Token dipilih: ${name} (${sym}) — saldo: ${bal} ]`,
    'status.copied':      '✅ Tersalin!',
    'status.signinRequired': '[ 🔐 Tanda tangani pesan di wallet kamu untuk membuka burn! ]',
    'status.signedIn':    '[ ✅ Terverifikasi! Wallet dikonfirmasi — siap burn. ]',
    'status.signSkipped': '[ 🔒 Burn terkunci. Tanda tangani pesan untuk membuktikan kamu bukan bot. ]',
    'picker.detecting': '⏳ Mendeteksi token ERC20 di wallet...',
    'picker.scanning':  (from, to, i, max) => `🔍 Scan block ${from}–${to} (${i}/${max})...`,
    'picker.checking':  (n) => `🔎 Memeriksa ${n} token kontrak...`,
    'picker.none':      (n) => `⚠️ Tidak ada token ERC20 terdeteksi dalam ~${n} block terakhir.`,
    'picker.empty':     '⚠️ Tidak ada token ERC20 dengan saldo > 0 ditemukan.',
    'picker.error':     '❌ Gagal memuat daftar token. Ketik address manual.',
    'wallet.install':   (key) => `${key} tidak terdeteksi.\nBuka halaman instalasi?`,
    'wallet.nowallet':  '[ ❌ Tidak ada wallet terdeteksi. ]',
	'footer.community': 'Komunitas',
    'footer.coffee': '☕ Traktir Saya Kopi (Base/ETH)',
    'footer.copyMsg': 'Alamat Disalin! Terima kasih kopinya! ☕',
  }
};

let currentLang = localStorage.getItem('ib_lang') || 'en';

function t(key, ...args) {
  const val = TRANSLATIONS[currentLang][key] || TRANSLATIONS['en'][key];
  if (typeof val === 'function') return val(...args);
  return val || key;
}

function applyLang() {
  document.documentElement.lang = currentLang;
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    const val = t(key);
    if (typeof val === 'string') el.textContent = val;
  });

  document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
    el.placeholder = t(el.getAttribute('data-i18n-placeholder'));
  });

  document.querySelectorAll('[data-i18n-title]').forEach(el => {
    el.title = t(el.getAttribute('data-i18n-title'));
  });

  document.getElementById('langEN').classList.toggle('active', currentLang === 'en');
  document.getElementById('langID').classList.toggle('active', currentLang === 'id');

  ['metamask','trust','coinbase','browser'].forEach(key => {
    const span = document.getElementById('status-' + key);
    if (!span) return;
    if (span.textContent.includes('✔') || span.textContent.includes('Terdeteksi') || span.textContent.includes('Detected')) {
      span.textContent = t('wallet.detected');
    } else if (span.textContent !== t('wallet.detecting')) {
      span.textContent = t('wallet.notFound');
    } else {
      span.textContent = t('wallet.detecting');
    }
  });
}

function setLang(lang) {
  currentLang = lang;
  localStorage.setItem('ib_lang', lang);
  applyLang();
}

applyLang();
